<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left._rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>e2b33fdd-8012-475d-8a36-8cbf891ecadf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.recaptcha.net/recaptcha/api2/payload?p=06ADUVZwDVpa0iQKyrIewM5JePyxu9_cveJqy3G4TWTA98V18PKVKed6EftOW9s-w4LZDvKmEHoFYVE2jMq8G9snGAfVetRWfgY2ikKxBSPs5SIuZVVg7jHKEB4_vk7dCJ-eoDgjTbzx9PIyEeGaJpTH4QIn935SJ2GWYgIBexCluYfvvS6r1VhdUjbxvnCPhMQ30oZz_KmbGwZYJqj7MBZAjyvQEMAzu8Ag&amp;k=6Lfu6R0nAAAAAI44YBsl8LEc3uUy_WhBhR1EOewe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PT ANTAM Tbk/iframe_html1body1div4div4iframe1_c-vnhzn3shm7ut</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.recaptcha.net/recaptcha/api2/payload?p=06ADUVZwDVpa0iQKyrIewM5JePyxu9_cveJqy3G4TWTA98V18PKVKed6EftOW9s-w4LZDvKmEHoFYVE2jMq8G9snGAfVetRWfgY2ikKxBSPs5SIuZVVg7jHKEB4_vk7dCJ-eoDgjTbzx9PIyEeGaJpTH4QIn935SJ2GWYgIBexCluYfvvS6r1VhdUjbxvnCPhMQ30oZz_KmbGwZYJqj7MBZAjyvQEMAzu8Ag&amp;k=6Lfu6R0nAAAAAI44YBsl8LEc3uUy_WhBhR1EOewe')])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
